arch:
 #- amd64
 - ppc64le
 - s390x
 #- arm64
 
os: bionic
language: java

jdk:
  - openjdk8
  #- openjdk11

script:
  - java -version
  - sudo apt update -y 
  - sudo apt install adoptopenjdk-8-hotspot -y 
