arch:
  - amd64
  - ppc64le
   
sudo: required
langauge: java

jdk:
  - openjdk8
  - openjdk15
  - orcalejdk8
  - orcalejdk11
  
script:
  - sudo apt-get update -y
  - sudo apt-cache search adoptopenjdk
