jobs:
include:
  - arch: amd64
  - arch: ppc64le
    dist: xenial
  - arch: ppc64le
    dist: bionic
  - arch: ppc64le
    dist: focal
   
  
jdk:
  - oraclejdk10
  
sudo: required

script:
  - sudo apt search adoptopenjdk
