jobs:
  include:
    - arch: ppc64le
      dist: xenial
    - arch: ppc64le
      dist: bionic
    - arch: ppc64le
      dist: focal
   
sudo: required
language: java
script:
  - sudo cat /etc/cloud/cloud.cfg
  - echo $DISTRIB_CODENAME
