jobs:
  include:
    - arch: s390x
      dist: xenial
    - arch: s390x
      dist: bionic
    - arch: s390x
      dist: focal
    # power jobs  
    - arch: ppc64le
      dist: xenial
    - arch: ppc64le
      dist: bionic
    - arch: ppc64le
      dist: focal
   
sudo: required
language: java
script:
  - sudo apt-get update -y
  - sudo apt-cache search adoptopenjdk
